### ISSUE TITLE
有關增加記錄名單

### ISSUE THREAD

**Issue by nekomix** [TaiwanVtuberData/TaiwanVtuberTrackingData#2]
你好 nh大大 

這裡是 貓耳 (貓耳未來 / 貓耳希望) TW/HK 雙人勢Vtuber.

看到所做的vtuber數據追蹤 不單指包括 台灣的Vtuber 還有包括其他地域的Vtuber
請問會否會對興趣其他地域的Vtuber也有興趣? (例如 香港Vtuber) ?

貓耳有相關頻道名單可以提供 希望也可以為華語V圈也儘一分力.

**Comment by nh60211as** [comment]
Finished importing Hong Kong Vtuber list.
